import {
  CHRISTMAS_PALETTES,
  HALLOWEEN_PALETTES,
  NEON_PALETTES,
  OCEAN_PALETTES,
  PASTEL_PALETTES,
  SUNSET_PALETTES,
  MONO_PALETTES,
  RETRO_PALETTES,
  FOREST_PALETTES,
  GALAXY_PALETTES,
  CANDY_PALETTES,
  ARCTIC_PALETTES,
  VALENTINE_PALETTES,
  SPRING_PALETTES,
  BIRTHDAY_PALETTES,
  GLITCH_PALETTES,
  ENIGMA_PALETTES,
} from "./palettes.js";

import {
  CHRISTMAS_SHAPES,
  HALLOWEEN_SHAPES,
  OCEAN_SHAPES,
  PASTEL_SHAPES,
  RETRO_SHAPES,
  CANDY_SHAPES,
  VALENTINE_SHAPES,
  BIRTHDAY_SHAPES,
  ENIGMA_SHAPES,
} from "./shapes.jsx";

import { loadSavedAchievements } from "../utils/storage.js";

export const PUZZLE_THEMES = [
  {
    id: "classic",
    name: "Classic",
    desc: "The original Agnus look",
    icon: null,
    palettes: null,
    shapes: null,
    decoration: null,
    gridBg: null,
    gridBorder: null,
    unlock: null,
    uiColors: null,
  },
  {
    id: "christmas",
    name: "Christmas",
    desc: "Festive reds, greens & gold",
    icon: "\uD83C\uDF84",
    palettes: CHRISTMAS_PALETTES,
    shapes: CHRISTMAS_SHAPES,
    decoration: "snow",
    gridBg: "#0d1a12",
    gridBorder: "#2E7D3266",
    unlock: { seasonal: 12, achievement: "streak_7" },
    uiColors: { bg: "#0a100a", surface: "#141f14", surfaceLight: "#1e2e1e", accent: "#d4a017", text: "#e8efe8", textDim: "#5b7b5b", border: "#2a3a2a" },
  },
  {
    id: "halloween",
    name: "Halloween",
    desc: "Spooky oranges & purples",
    icon: "\uD83C\uDF83",
    palettes: HALLOWEEN_PALETTES,
    shapes: HALLOWEEN_SHAPES,
    decoration: "bats",
    gridBg: "#14080a",
    gridBorder: "#7B1FA266",
    unlock: { seasonal: 10, achievement: "total_100" },
    uiColors: { bg: "#0f0a10", surface: "#1a1420", surfaceLight: "#2a1e30", accent: "#ff8c00", text: "#e8e0ef", textDim: "#7b6b8b", border: "#3a2a4a" },
  },
  {
    id: "neon",
    name: "Neon",
    desc: "Electric glow in the dark",
    icon: "\u26A1",
    palettes: NEON_PALETTES,
    shapes: null,
    decoration: "glow",
    gridBg: "#050510",
    gridBorder: "#FF008066",
    unlock: { achievement: "gold_25" },
    uiColors: { bg: "#050510", surface: "#0a0a1f", surfaceLight: "#14142e", accent: "#ff0080", text: "#e0e8ff", textDim: "#6b6bab", border: "#2a2a5a" },
  },
  {
    id: "ocean",
    name: "Ocean",
    desc: "Deep sea blues & corals",
    icon: "\uD83C\uDF0A",
    palettes: OCEAN_PALETTES,
    shapes: OCEAN_SHAPES,
    decoration: "bubbles",
    gridBg: "#071318",
    gridBorder: "#0277BD44",
    unlock: { achievement: "med_50" },
    uiColors: { bg: "#060d14", surface: "#0e1820", surfaceLight: "#162230", accent: "#00bcd4", text: "#d8e8f0", textDim: "#5b7b8b", border: "#1a3040" },
  },
  // --- Easy unlocks ---
  {
    id: "pastel",
    name: "Pastel",
    desc: "Soft & dreamy colours",
    icon: "\uD83C\uDF38",
    palettes: PASTEL_PALETTES,
    shapes: PASTEL_SHAPES,
    decoration: "petals",
    gridBg: "#18141e",
    gridBorder: "#E8BAFF44",
    unlock: { achievement: "first_try" },
    uiColors: { bg: "#100e14", surface: "#1a1820", surfaceLight: "#24202e", accent: "#e8a0d0", text: "#f0e8f5", textDim: "#8b7b9b", border: "#302a3a" },
  },
  {
    id: "sunset",
    name: "Sunset",
    desc: "Warm golden hour vibes",
    icon: "\uD83C\uDF05",
    palettes: SUNSET_PALETTES,
    shapes: null,
    decoration: "rays",
    gridBg: "#1a120a",
    gridBorder: "#FF6B3544",
    unlock: { achievement: "easy_5" },
    uiColors: { bg: "#100a06", surface: "#1f1410", surfaceLight: "#2e1e18", accent: "#ff8c42", text: "#f0e8e0", textDim: "#8b7b6b", border: "#3a2a1a" },
  },
  {
    id: "mono",
    name: "Monochrome",
    desc: "Elegant shades of grey",
    icon: "\u25D1",
    palettes: MONO_PALETTES,
    shapes: null,
    decoration: null,
    gridBg: "#111114",
    gridBorder: "#52525B44",
    unlock: { achievement: "under_30" },
    uiColors: { bg: "#0c0c0e", surface: "#161618", surfaceLight: "#202022", accent: "#a0a0a8", text: "#d8d8dc", textDim: "#68686e", border: "#303034" },
  },
  // --- Medium unlocks ---
  {
    id: "retro",
    name: "Retro Arcade",
    desc: "80s pixel power",
    icon: "\uD83D\uDD79\uFE0F",
    palettes: RETRO_PALETTES,
    shapes: RETRO_SHAPES,
    decoration: "scanlines",
    gridBg: "#0a0a14",
    gridBorder: "#FF005444",
    unlock: { achievement: "med_5" },
    uiColors: { bg: "#0a0a14", surface: "#14142a", surfaceLight: "#1e1e3a", accent: "#ff0054", text: "#e8e8ff", textDim: "#6b6b9b", border: "#2a2a4a" },
  },
  {
    id: "forest",
    name: "Forest",
    desc: "Deep woodland greens",
    icon: "\uD83C\uDF32",
    palettes: FOREST_PALETTES,
    shapes: null,
    decoration: "leaves",
    gridBg: "#0c140e",
    gridBorder: "#2D6A4F44",
    unlock: { achievement: "streak_3" },
    uiColors: { bg: "#080e0a", surface: "#101a12", surfaceLight: "#18241a", accent: "#4caf50", text: "#d8e8da", textDim: "#5b7b5d", border: "#1a3a1e" },
  },
  {
    id: "galaxy",
    name: "Galaxy",
    desc: "Cosmic purples & stardust",
    icon: "\uD83C\uDF0C",
    palettes: GALAXY_PALETTES,
    shapes: null,
    decoration: "stars",
    gridBg: "#080810",
    gridBorder: "#7B2FF744",
    unlock: { achievement: "gold_10" },
    uiColors: { bg: "#080810", surface: "#10101e", surfaceLight: "#1a1a2e", accent: "#9c6bff", text: "#e0e0f0", textDim: "#7070a0", border: "#2a2a50" },
  },
  {
    id: "candy",
    name: "Candy Shop",
    desc: "Sweet treats & bright pinks",
    icon: "\uD83C\uDF6C",
    palettes: CANDY_PALETTES,
    shapes: CANDY_SHAPES,
    decoration: "sprinkles",
    gridBg: "#1a0e16",
    gridBorder: "#FF6B9D44",
    unlock: { achievement: "cascade_1" },
    uiColors: { bg: "#120a10", surface: "#1e1218", surfaceLight: "#2a1a22", accent: "#ff6b9d", text: "#f0e0ea", textDim: "#9b6b8b", border: "#3a2232" },
  },
  // --- Harder / Seasonal unlocks ---
  {
    id: "arctic",
    name: "Arctic",
    desc: "Icy blues & northern lights",
    icon: "\u2744\uFE0F",
    palettes: ARCTIC_PALETTES,
    shapes: null,
    decoration: "aurora",
    gridBg: "#060d14",
    gridBorder: "#38BDF844",
    unlock: { seasonal: 1, achievement: "hard_5" },
    uiColors: { bg: "#060a10", surface: "#0c1420", surfaceLight: "#141e30", accent: "#38bdf8", text: "#d8e8f8", textDim: "#5b7b9b", border: "#1a2a40" },
  },
  {
    id: "valentine",
    name: "Valentine",
    desc: "Hearts, roses & love",
    icon: "\u2764\uFE0F",
    palettes: VALENTINE_PALETTES,
    shapes: VALENTINE_SHAPES,
    decoration: "hearts",
    gridBg: "#1a0a10",
    gridBorder: "#FF2D5544",
    unlock: { seasonal: 2, achievement: "daily_7" },
    uiColors: { bg: "#100608", surface: "#1e0e12", surfaceLight: "#2e161e", accent: "#ff4d6d", text: "#f0e0e4", textDim: "#9b6b7b", border: "#3a1a24" },
  },
  {
    id: "spring",
    name: "Spring",
    desc: "Fresh blossoms & sunshine",
    icon: "\uD83C\uDF3C",
    palettes: SPRING_PALETTES,
    shapes: PASTEL_SHAPES,
    decoration: "springPetals",
    gridBg: "#0a1410",
    gridBorder: "#10B98144",
    unlock: { seasonal: [3, 4, 5], achievement: "all_modes" },
    uiColors: { bg: "#080e08", surface: "#101a10", surfaceLight: "#182418", accent: "#10b981", text: "#d8f0d8", textDim: "#5b8b5b", border: "#1a3a1a" },
  },
  {
    id: "birthday",
    name: "Birthday",
    desc: "Celebrate with confetti & cake",
    icon: "\uD83C\uDF82",
    palettes: BIRTHDAY_PALETTES,
    shapes: BIRTHDAY_SHAPES,
    decoration: "confetti",
    gridBg: "#1a0e18",
    gridBorder: "#FF6B9D44",
    unlock: { achievement: "birthday_puzzle" },
    uiColors: { bg: "#100810", surface: "#1e1018", surfaceLight: "#2a1822", accent: "#ff69b4", text: "#f0e0f0", textDim: "#9b6b9b", border: "#3a1a3a" },
  },
  {
    id: "glitch",
    name: "Glitch",
    desc: "Embrace the beautiful errors",
    icon: "\uD83D\uDC80",
    palettes: GLITCH_PALETTES,
    shapes: null,
    decoration: "static",
    gridBg: "#080008",
    gridBorder: "#FF004044",
    unlock: { achievement: "first_fail" },
    uiColors: { bg: "#080008", surface: "#140010", surfaceLight: "#1e0018", accent: "#ff0040", text: "#e0d0e0", textDim: "#8b5b7b", border: "#3a0a2a" },
  },
  // --- Secret Enigma theme — unlocked via Alan Turing birthday easter egg ---
  {
    id: "enigma",
    name: "Enigma",
    desc: "The code has been broken",
    icon: null,
    palettes: ENIGMA_PALETTES,
    shapes: ENIGMA_SHAPES,
    decoration: "rotors",
    gridBg: "#0c0c08",
    gridBorder: "#C9A84C33",
    unlock: { achievement: "cheat_turing" },
    uiColors: { bg: "#0a0a06", surface: "#14140e", surfaceLight: "#1e1e16", accent: "#c9a84c", text: "#e8e8d8", textDim: "#7b7b5b", border: "#2a2a1a" },
  },
];

export function isThemeUnlocked(theme, achievementsList) {
  if (!theme.unlock) return true;
  const now = new Date();
  const currentMonth = now.getMonth() + 1;
  if (theme.unlock.seasonal) {
    const months = Array.isArray(theme.unlock.seasonal) ? theme.unlock.seasonal : [theme.unlock.seasonal];
    if (months.includes(currentMonth)) return true;
  }
  if (theme.unlock.achievement && achievementsList) {
    const ach = achievementsList.find(a => a.id === theme.unlock.achievement);
    if (ach && ach.unlocked) return true;
  }
  // Fallback: check saved achievements directly (e.g. cheat_turing persisted via easter egg)
  if (theme.unlock.achievement) {
    try {
      const saved = loadSavedAchievements();
      if (saved.has(theme.unlock.achievement)) return true;
    } catch { /* ignore */ }
  }
  return false;
}
